### ISSUE TITLE
upper bound python requirements is making the plugin impossible to install with poetry

### ISSUE THREAD

**Issue by Tobi-De** [mondeja/mkdocs-include-markdown-plugin#135]
Hi, I hope you are doing great, thanks for this amazing plugin.

I'm trying to install this plugin using poetry but because of the `requires-python = ">=3.7,<3.12"` line in your `pyproject.toml`file it is impossible to install the package without updating my project to have the same constraints. I'm using poetry here but I'm sure the issue will occur with other package managers as well.
The easiest solution would be to remove the `<3.12` upper bound, is there a reason why it is needed?

**Comment by mondeja** [comment]
I don't understand why you are not able to install it with Poetry, are you trying to install in Python 3.12?

**Comment by Tobi-De** [comment]
In most cases it is recommended to avoid setting upper limit on python requirements, you can read [this](https://discuss.python.org/t/requires-python-upper-limits/12663) for a more detailed explanation, thanks.

**Comment by mondeja** [comment]
> Since this plugin defines the python requirements as ">=3.7,<3.12", my project and the plugin is now incompatible.

That doesn't makes sense, please report the problem to Poetry.

**Comment by Tobi-De** [comment]
> > In poetry this translate to ">=3.8<4.0"
> > Since this plugin defines the python requirements as ">=3.7,<3.12", my project and the plugin is now incompatible.
> 
> That doesn't makes sense, please report the problem to Poetry.

I could fix the issue myself by just changing my python constraints to the same as yours :

```toml
python=">=3.7,<3.12
```

But the issue is that everybody won't do the same, some people may just assume something is wrong with this package. Like I said this has nothing to do with peotry really, most package manager that generate a `pyproject.toml` file do not set an upper limit to the python requirement, basically it's generally something like `python>=3.7`
I generated a project recently with hatch and if I remember correctly, they too do not set the upper limit, generally it is recommended to not do so.

**Comment by Tobi-De** [comment]
But this is no big deal don't worry, in my case I'll just stick with the latest version before the 4.0.0 which is 3.9.2 I think.
Feel free to close this issue

**Comment by mondeja** [comment]
Sorry, Poetry is not following [PEP 345](https://peps.python.org/pep-0345/#requires-python):

> [Requires-Python](https://peps.python.org/pep-0345/#requires-python)
>
> This field specifies the Python version(s) that the distribution is guaranteed to be compatible with.

I don't understand why Poetry adds the limit <4.0 and why they don't document their specification, so I suspect that they don't follow a specification at all. Have used Poetry in the past trying to transit to *pyproject.toml* and in my experience has been the worst package manager ever used for a lot of reasons.

I'm not against removing the upper limit if someone could explain me with arguments why, I'm not going to remove it breaking PEP 345 just because Poetry guys are creating their own internal specification which the others can't read.

**Comment by ofek** [comment]
> I'm not against removing the upper limit if someone could explain me with arguments why

https://iscinumpy.dev/post/bound-version-constraints/

**Comment by mondeja** [comment]
> > I'm not against removing the upper limit if someone could explain me with arguments why
> 
> https://iscinumpy.dev/post/bound-version-constraints/

https://github.com/python-poetry/poetry/issues/5823

**Comment by mondeja** [comment]
Hi, I want to give some reasonable feedback about why I'm not going to accept this. If someone is capable of answering the next question I would change my opinion about it, but doesn't seem possible: how should I suppose to get the maximum version of Python that my program supports at runtime without hardcoding it?

I've faced a situation in which I need it, see [this function](https://github.com/mondeja/project-config/pull/172/files#diff-a7744cc9938238f9c0750b502b89f21445acc1617c85930bee77a06168d96e36R56-R69). Using `importlib-metadata` and some linting over `Requires-Python` equivalent on Hatch (I'm checking with [project-config](https://github.com/mondeja/project-config) that the field [matches the regular expression `^>=\d+\.\d+,<\d+\.\d+$`](https://github.com/mondeja/project-config-styles/blob/f6177f1803fb77e4a01f4d4cf182653cdbe1d67f/python/version/main.json5#L10-L19)) I can get it. That provides me a way to deterministically get the maximum version of Python supported by my program with a simple regex search call.

It would be great if a standard could set the maximum version recommended (not allowed) for Python programs without conflicting with the behaviour of Poetry. But IHMO, the promise of reproducible installation on all environments at the cost of breaking PEP 345 is not a solution at all if the community doesn't have a way to indicate to their programs this crucial information.

Take into account that I've been able to write the function in the first place just because I'm following the standard of quality defined by [my project-config styles](https://github.com/mondeja/project-config-styles), so if I change the value of `Requires-Python` the linting does not pass. This tool also allow me to support Python version changes in a library just changing this major boundary in the metadata of the *pyproject.toml*, because it is connected with other configurations for `mypy:python_version`, `isort:py_version`...
