### ISSUE TITLE
Dedent doesn't work when using 4 spaces for indentation

### ISSUE THREAD

**Issue by prcr** [mondeja/mkdocs-include-markdown-plugin#151]
Setting `dedent=true` doesn't work **when using 4 spaces** to indent content nested in list items.

For example, the following list item includes the nested "Text to include":

![image](https://user-images.githubusercontent.com/60105800/214563142-b564e2ef-1710-44f6-9376-ab0b62fa476b.png)

```markdown
1.  This is a list item

    <!--test-start-->
    Text to include
    <!--test-end-->
```

However, when importing, the text appears rendered as a code block because the dedent doesn't work in this case:

![image](https://user-images.githubusercontent.com/60105800/214562983-680b6a0f-3c0d-46f7-987b-a761802adae3.png)

```
{%
    include-markdown "test.md"
    start="<!--test-start-->"
    end="<!--test-end-->"
    dedent=true
%}
```

The dedent works correctly only if I use 2 spaces to indent the nested text.

I tried to understand why this happens, but since the plugin uses the `textwrap.dedent()` library function I'm unsure why this doesn't work with larger indentations. :thinking:

**Comment by mondeja** [comment]
Your case can be solved easily, just don't add newlines:

```markdown
1.  This is a list item
    
    <!--test-start-->Text to include<!--test-end-->
```

### Why `start` and `end` context is ignored

mkdocs-include-markdown-plugin just includes content based on `start` and `end` markers, but doesn't know about the context in which these markers are placed. This approach is much more intuitive than changing the content to include based in the block of the marker.

In your case is including literally the content after `<--test-start-->` which starts with a newline character followed by 4 spaces before `"Text to include"`, which is indeed an indented code block.

The problem is that, in the Mkdocs ecosystem there is no a standarized way to write Markdown, as each plugin or extension implements its own syntax. Is a bit wilder but comes with a lot of flexibility. Mkdocs Markdown parser does not complain about any syntax. So is not totally clear when we are parsing a nested block. In your example is a list item block inside an unordered list block, but could be cases that wouldn't be.

That's why I prefer to maintain this approach than changing the content to unobvious preferences that could lead to strange failures when used in conjunction with other plugins and extensions.
