### ISSUE TITLE
Is it necessary to set the "require_python" upper bound to <3.13

### ISSUE THREAD

**Issue by tyong920** [mondeja/mkdocs-include-markdown-plugin#176]
Downstream libraries or programs are limited by this ...

**Comment by mondeja** [comment]
And that's correct, we don't know yet if the library works in Python3.13. If you are very concerned about that, switch from poetry to hatch.

**Comment by GabDug** [comment]
`hatch` is a great tool, but it does not come with reproducibility as there is no lockfile, and thus may not fit for all needs.

I've tested with PDM and Poetry, and both will install 3.9.1 if I don't specify an upper-bound on my project, as it's the last-version with no upper-bound.

Fortunately, PDM allow me to override this behaviour, but I'm sure most users won't notice, just like I've been using an older version for months.

This is a really useful tool, so I hope you'll reconsider this position :)

Have a nice day!

**Comment by GabDug** [comment]
While `hatch` is a great tool, it's not suitable for all use-cases: due to the absence of a standard lockfile format, there is no reproducibility.

I've read your arguments in #135, and one of your point is that it's supposed to indicate versions that are *guaranteed* compatible, as per the [Core metadata specifications](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-python). While I agree that there is no guarantee it works on Python 3.13, I think it's okay to assume forward compatibility between Python versions. 
Moreover, this is what the majority of packages do, and it's also what the specifications indicates in its example. Even PyPA, the maintainers of the specification, do not specify upper-bounds on their projects like [setuptools](https://pypi.org/project/setuptools/) or [pip](https://pypi.org/project/pip/#data).

I agree that removing the upper-bound also removes information that is easily parseable. However, the ecosystem use alternative ways, and instead convey this kind of information through standard, parseable classifiers, and to humans with badges and documentation.

Finally, if compatibility with future versions is a concern, simply adding a warning and disclaimer when running on a an unsupported-version of Python may be a fair approach.

I'll hope you'll reconsider :) 

Have a great day, and thanks for this really useful package!

**Comment by mondeja** [comment]
> However, the ecosystem use alternative ways, and instead convey this kind of information through standard, parseable classifiers

I haven't considered to use classifiers as a way to parse the upper version bound. Thanks. Seems feasible but I need to make some changes in the tool that I use to standarize the configuration across projects. Reopening this issue... expect it to be acomplished in a few weeks.

**Comment by tyong920** [comment]
> While `hatch` is a great tool, it's not suitable for all use-cases: due to the absence of a standard lockfile format, there is no reproducibility. PDM or Poetry are reasonable choices when this is a requirement.
> 
> I've read your arguments in #135, and one of your point is that it's supposed to indicate versions that are _guaranteed_ compatible, as per the [Core metadata specifications](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-python). While I agree that there is no guarantee it works on Python 3.13, I think it's okay to assume forward compatibility between Python versions. Moreover, this is what the majority of packages do, and it's also what the specifications indicates in its example. Even PyPA, the maintainers of the specification, do not specify upper-bounds on their projects like [setuptools](https://pypi.org/project/setuptools/) or [pip](https://pypi.org/project/pip/#data).
> 
> I agree that removing the upper-bound also removes information that is easily parseable. However, the ecosystem use alternative ways, and instead convey this kind of information through standard, parseable classifiers, and to humans with badges and documentation.
> 
> Finally, if compatibility with future versions is a concern, simply adding a warning and disclaimer when running on a an unsupported-version of Python may be a fair approach.
> 
> I'll hope you'll reconsider :)
> 
> Have a great day, and thanks for this really useful package!

Could't agree more! 👍

**Comment by mondeja** [comment]
The new version [6.0.2](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v6.0.2) does not include a maximum Python upper version as requirement.
