### ISSUE TITLE
Paths relative to docs folder

### ISSUE THREAD

**Issue by mirk8s** [mondeja/mkdocs-include-markdown-plugin#55]
The following example in the README isn't working as expected.

> {%
> include-markdown "docs/includes/header.md"
> heading-offset=1
> %}

A custom setting for the plugin (or an already existing global one?) should be set to specify docs root path, e.g.:

**mkdocs.yml**
```
plugins:
  - include-markdown:
      docs_root: 'docs'
```

so that each relative path is interpreted as relative to `docs_root`.

**Comment by mondeja** [comment]
Sorry to take so long to answer. As far as I know, this doesn't make sense because the links could point to an inexistent page in the Mkdocs build. Furthermore, Mkdocs encourages users to use properly relative links: are relative to the file where are defined. See [Internal Links](https://www.mkdocs.org/user-guide/writing-your-docs/#internal-links) for more.
