### ISSUE TITLE
rewrite_relative_urls seems to be broken

### ISSUE THREAD

**Issue by facontidavide** [mondeja/mkdocs-include-markdown-plugin#88]
**rewrite_relative_urls** doesn't work for me. Please find attached a simple project to reproduce the issue.

Output 

```
$ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
WARNING  -  Documentation file 'index.md' contains a link to '../src/images/hello.png' which is not found in the documentation files.
INFO     -  Documentation built in 0.05 seconds
INFO     -  [19:41:47] Serving on http://127.0.0.1:8000/
WARNING  -  [19:41:48] "GET /pounce_teleop/ HTTP/1.1" code 404
```

[mkdocs_test.zip](https://github.com/mondeja/mkdocs-include-markdown-plugin/files/7928044/mkdocs_test.zip)

**Comment by mondeja** [comment]
Your example project works as expected. The output that I see:

![image](https://user-images.githubusercontent.com/23049315/150908325-d06c80b3-0a50-4519-8ae5-86e719ba5b67.png)

But I don't know what to expect, could you share more information about your problem?

**Comment by facontidavide** [comment]
Does not work as expected for me

![image](https://user-images.githubusercontent.com/2822888/150952195-8c7e9245-33f7-4067-8969-081307f917db.png)

**Comment by mondeja** [comment]
Could you share the Mkdocs configuration? At least the relevants parts that could be related to this bug.

**Comment by mondeja** [comment]
This is the expected behaviour in Mkdocs. If you uninstall the plugin and define the link directly in `docs/index.md` with `![image](../src/images/hello.png)`, the same happens running `serve` command. The warning shown is very clear:

```
Documentation file 'index.md' contains a link to '../src/images/hello.png' which is not found in the documentation files.
```

If you moves `src/images` folder to `docs/images` and define the link with `![image](images/hello.png)`, works as expected without the warning. So nothing to do with the plugin.
